### ISSUE TITLE
Mysteriously breaks

### ISSUE THREAD

**Issue by perguth** [pguth/yrn#20]
```bash
Done in 2.34s.
fs.js:913
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/per/Github/playground/node_modules'
    at Object.fs.readdirSync (fs.js:913:18)
    at getDirectories (/usr/local/lib/node_modules/yrn/bin.js:65:13)
    at restorePackagesAndSymlinks (/usr/local/lib/node_modules/yrn/bin.js:100:22)
    at ChildProcess.x (/usr/local/lib/node_modules/yrn/bin.js:48:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```
Couldn't pinpoint it so far.

**Comment by perguth** [comment]
Can't reproduce.
